### ISSUE TITLE
macOS: Shortcuts are broken on "Dvorak-Qwerty ⌘" layout

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#7315]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/5466

<div type='discussions-op-text'>

<sup>Originally posted by **Viknet** January 31, 2025</sup>
"Dvorak-Qwerty ⌘" transmorphic layout uses the Dvorak layout for unmodified keystrokes, but unlike the “normal” Dvorak layout, it actually retains the QWERTY layout for keys when pressed in combination with the ⌘ modifier.
For example: if i press key "v" on a keyboard, letter "k" will print out. But if I hold ⌘ and press key "v", it should activate "⌘+v" shortcut and do paste from clipboard.

After recent update to version 1.1.0 (build 9283, commit [facda0c3](https://github.com/ghostty-org/ghostty/commits/facda0c3)) shortcuts with ⌘ modifier behave like it's regular Dvorak layout.
Now when I hold ⌘ and press key "v" it activates "⌘+k" shortcut.</div>

**Comment by gustafnk** [comment]
I don't know if this is related or something new, but since a little while back the behaviour for "zoom in" action in Ghostty changed for me, from what most other macOS applications use to using another key.

I'm using regular english Dvorak in macOS, *but* my keyboard has Swedish layout (since I live in Sweden, it's easier to get hold on laptops with Swedish layouts).

- The old behaviour: zoom in using ⌘-=/+ key, this is what all other applications do in my scenario
- The new behaviour: zoom in using ⌘-]/} key, this is unusual behaviour in my scenario

See attached screenshot below for macOS Keyboard Viewer.

<img width="603" height="328" alt="Image" src="https://github.com/user-attachments/assets/f2e8065f-f9c6-4622-9463-7b524a54f269" />

If I search the web, I can see that native US english macs have their =/+ key just left of the backspace key (see screenshot below). And for me, the physical key next just left of the backspace key *is* the ]/} key. So, this somewhat explains the behaviour – Ghostty is somewhat using the "hardware" key when pressing ⌘ and not using my "software" key. Sorry about possibly using the wrong terminology, it's not my technical domain...

<img width="598" height="231" alt="Image" src="https://github.com/user-attachments/assets/44a58125-273d-4511-bea3-fc417c983d52" />

I do realize I'm in a niche group of users, but I just wanted to give a heads-up that the behaviour seems to be newly introduced (AFAIK) and that the behaviour is not aligned with other macOS applications.

I'm both on macOS 25 and 26 (updated a few days ago).

I'd be happy to test older versions of Ghostty, if that would be valuable.

Thanks for making Ghostty! 🙌

**Comment by gyzerok** [comment]
It seems like the issue is fixed but it sort of introduces new issue.

Before this fix I only CMD+V on the Dvorak layout would work. Even though with CMD pressed it should work only on QWERTY. Now CMD+V works on both layouts which is probably not intentional.

@mitchellh should the issue be reopened?

**Comment by mikeyward** [comment]
Issue with ⌘+ still exists in 1.2.3 using standard Dvorak keyboard layout on macOS. In part because of the = key.

According to Ghostty's keybind docs, key names like `equal` and `minus` match physical key positions (W3C key codes), not the logical character from keyboard layout. Only single Unicode codepoint triggers match logically — and since = can't be used as a trigger (it's the keybind separator), equal is a physical key name.

So the only workaround I've found is to add a specific keybind for the bracket-right hardware key:
`keybind = super+bracket_right=increase_font_size:1`

**Comment by danielwe** [comment]
> since = can't be used as a trigger

You can use `=` as a trigger, and it will work if your layout has a key that inserts `=` directly without using shift/opt/altgr. Just do `keybind = super+==increase_font_size:1`. I doesn't look pretty, but I just confirmed that `keybind = cmd+==new_window` works with a US layout.

In short:
- `equal` refers to the physical key that inserts `=` on a US layout
- `=` is a unicode trigger and matches whatever key you have that inserts "=" unshifted
- Ghostty is currently not able to match unicode triggers to shifted keys. That is, if your layout requires shift, opt, or altgr to type "=", you won't be able to use `=` as a keybind trigger.
  - Partial workaround on macOS: if you bind a unicode-based trigger to an action that has an entry in the menu bar, macOS will consume the key event and trigger the menu action rather than passing the event to Ghostty. Since macOS _does_ match unicode triggers to shifted keys, such triggers work for menu actions. (Fine print: if multiple triggers are bound to the same action, only the one that's actually shown in the menu gets special treatment. Also, this only works when the app is in focus, so can't help you with global keybinds.)

**Comment by gyzerok** [comment]
For me in the latest version doing CMD+(QWERTY)W does not work, it opens config instead, however CMD+(DVORAK)W does work. So I think the issues should be reopened.
